FROM pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel

RUN apt update && apt install -y \
    wget \
    git \
    nano \
    curl \
    unzip \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip \
    &&  pip install --no-cache-dir \
        black==22.3.0 \
        jupyterlab==3.4.2 \
        jupyterlab_code_formatter==1.4.11 \
        lckr-jupyterlab-variableinspector==3.0.9 \
        jupyterlab_widgets==1.1.0 \
        ipywidgets==7.7.0 \
        import-ipynb==0.1.4 \
        huggingface_hub[cli] \
        wandb

RUN python3 -m pip install --no-cache-dir \
    transformers==4.44.2 \
    datasets \
    trl \
    accelerate \
    bitsandbytes \
    optimum \
    peft \
    deepspeed \
    ninja \
    fugashi \
    unidic_lite \
    sentencepiece \
    wheel
    
RUN python3 -m pip install flash-attn --no-build-isolation

RUN apt-get autoremove -y &&\
    apt-get clean

ENV user contuser1

RUN useradd -u 1000 -m -d /workspace/audit_llm usk \
     && chown -R usk /workspace/audit_llm
    
    USER usk

WORKDIR /workspace/audit_llm

